### ISSUE TITLE
Error while exporting pg_id_string

### ISSUE THREAD

**Issue by sabarishsubramanian** [InsightByte/ApacheNifi#1]
export pg_id_string=`echo $resources| jq -c '.resources[] | select(.name| contains ("'NiFi Flow'")) | .identifier' | grep -v 'data\|policies\|operation' | grep 'process-groups' | tr -d '"'`
jq: error: syntax error, unexpected $end, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Unix shell quoting issues?) at <top-level>, line 1:
.resources[] | select(.name| contains ("NiFi                                        
jq: 1 compile error

**Comment by InsightByte** [comment]
strange, it work for me.
this is what you try to run ? 
```
export resources=`curl -XGET http://$nifi_host:$nifi_port/nifi-api/resources`
export pg_name='NiFi Flow'
export pg_id_string=`echo $resources| jq -c '.resources[] | select(.name| contains ("'$pg_name'")) | .identifier' | grep -v 'data\|policies\|operation' | grep 'process-groups' | tr -d '"'`
```

**Comment by sabarishsubramanian** [comment]
yes, I tried the above command only.


 export pg_id_string=`echo $resources| jq -c '.resources[] | select(.name| contains ("'$pg_name'")) | .identifier' | grep -v 'data\|policies\|operation' | grep 'process-groups' | tr -d ' " '`
jq: error: syntax error, unexpected $end, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Unix shell quoting issues?) at <top-level>, line 1:
.resources[] | select(.name| contains ("NiFi                                        
jq: 1 compile error

**Comment by InsightByte** [comment]
ok, when you run 
`export resources=`curl -XGET http://$nifi_host:$nifi_port/nifi-api/resources``
do you get anything back in the resource param?
do echo `$resources`

**Comment by sabarishsubramanian** [comment]
yes i do get.

echo $resources
{"resources":[{"identifier":"/flow","name":"NiFi Flow"},{"identifier":"/system","name":"System"},{"identifier":"/controller","name":"Controller"},{"identifier":"/counters","name":"Counters"},{"identifier":"/provenance","name":"Provenance"},{"identifier":"/policies","name":"Access Policies"},{"identifier":"/tenants","name":"Tenant"},{"identifier":"/proxy","name":"Proxy User Requests"},{"identifier":"/resources","name":"NiFi Resources"},{"identifier":"/site-to-site","name":"Site to Site"},{"identifier":"/parameter-contexts","name":"Parameter Contexts"},{"identifier":"/restricted-components","name":"Restricted Components"},{"identifier":"/restricted-components/read-filesystem","name":"read filesystem"},{"identifier":"/restricted-components/write-filesystem","name":"write filesystem"},{"identifier":"/restricted-components/read-distributed-filesystem","name":"read distributed filesystem"},{"identifier":"/restricted-components/write-distributed-filesystem","name":"write distributed filesystem"},{"identifier":"/restricted-components/execute-code","name":"execute code"},{"identifier":"/restricted-components/access-keytab","name":"access keytab"},{"identifier":"/restricted-components/access-ticket-cache","name":"access ticket cache"},{"identifier":"/restricted-components/export-nifi-details","name":"export nifi details"},{"identifier":"/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"NiFi Flow"},{"identifier":"/data/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Data for NiFi Flow"},{"identifier":"/provenance-data/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Provenance data for NiFi Flow"},{"identifier":"/policies/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Policies for NiFi Flow"},{"identifier":"/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"PutMongoRecord"},{"identifier":"/data/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Operations forPutMongoRecord"},{"identifier":"/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"PutMongoRecord"},{"identifier":"/data/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Operations forPutMongoRecord"},{"identifier":"/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"GetSFTP"},{"identifier":"/data/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Operations forGetSFTP"},{"identifier":"/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"SplitJson"},{"identifier":"/data/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Data for SplitJson"},{"identifier":"/provenance-data/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Provenance data for SplitJson"},{"identifier":"/policies/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Policies for SplitJson"},{"identifier":"/operation/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Operations forSplitJson"},{"identifier":"/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"PutMongoRecord"},{"identifier":"/data/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Operations forPutMongoRecord"},{"identifier":"/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"GetSFTP"},{"identifier":"/data/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Operations forGetSFTP"},{"identifier":"/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"ConsumeKafka_2_6"},{"identifier":"/data/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Data for ConsumeKafka_2_6"},{"identifier":"/provenance-data/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Provenance data for ConsumeKafka_2_6"},{"identifier":"/policies/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Policies for ConsumeKafka_2_6"},{"identifier":"/operation/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Operations forConsumeKafka_2_6"},{"identifier":"/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"PutMongoRecord"},{"identifier":"/data/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Operations forPutMongoRecord"},{"identifier":"/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"PutMongoRecord"},{"identifier":"/data/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Operations forPutMongoRecord"},{"identifier":"/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"GetSFTP"},{"identifier":"/data/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Operations forGetSFTP"},{"identifier":"/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"ConsumeKafka_2_6"},{"identifier":"/data/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Data for ConsumeKafka_2_6"},{"identifier":"/provenance-data/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Provenance data for ConsumeKafka_2_6"},{"identifier":"/policies/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Policies for ConsumeKafka_2_6"},{"identifier":"/operation/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Operations forConsumeKafka_2_6"},{"identifier":"/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"SplitJson"},{"identifier":"/data/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Data for SplitJson"},{"identifier":"/provenance-data/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Provenance data for SplitJson"},{"identifier":"/policies/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Policies for SplitJson"},{"identifier":"/operation/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Operations forSplitJson"},{"identifier":"/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"flow"},{"identifier":"/data/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Data for flow"},{"identifier":"/provenance-data/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Provenance data for flow"},{"identifier":"/policies/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Policies for flow"},{"identifier":"/operation/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Operations forflow"},{"identifier":"/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"MongoDBControllerService"},{"identifier":"/policies/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Policies for MongoDBControllerService"},{"identifier":"/operation/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Operations forMongoDBControllerService"},{"identifier":"/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"CSVReader"},{"identifier":"/policies/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Policies for CSVReader"},{"identifier":"/operation/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Operations forCSVReader"},{"identifier":"/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"HBase_1_1_2_ClientService"},{"identifier":"/policies/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Policies for HBase_1_1_2_ClientService"},{"identifier":"/operation/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Operations forHBase_1_1_2_ClientService"},{"identifier":"/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"JsonTreeReader"},{"identifier":"/policies/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Policies for JsonTreeReader"},{"identifier":"/operation/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Operations forJsonTreeReader"},{"identifier":"/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"MongoDBControllerService"},{"identifier":"/policies/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Policies for MongoDBControllerService"},{"identifier":"/operation/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Operations forMongoDBControllerService"},{"identifier":"/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"CSVReader"},{"identifier":"/policies/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Policies for CSVReader"},{"identifier":"/operation/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Operations forCSVReader"},{"identifier":"/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"HBase_1_1_2_ClientService"},{"identifier":"/policies/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Policies for HBase_1_1_2_ClientService"},{"identifier":"/operation/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Operations forHBase_1_1_2_ClientService"},{"identifier":"/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"JsonTreeReader"},{"identifier":"/policies/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Policies for JsonTreeReader"},{"identifier":"/operation/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Operations forJsonTreeReader"},{"identifier":"/templates/bd548bb1-87a0-4384-9fb5-06de55df2350","name":"test"},{"identifier":"/policies/templates/bd548bb1-87a0-4384-9fb5-06de55df2350","name":"Policies for test"}]}

**Comment by InsightByte** [comment]
I have just ran the code using this as input and it worked with no issues. So can you run this ?
```
export resources='{"resources":[{"identifier":"/flow","name":"NiFi Flow"},{"identifier":"/system","name":"System"},{"identifier":"/controller","name":"Controller"},{"identifier":"/counters","name":"Counters"},{"identifier":"/provenance","name":"Provenance"},{"identifier":"/policies","name":"Access Policies"},{"identifier":"/tenants","name":"Tenant"},{"identifier":"/proxy","name":"Proxy User Requests"},{"identifier":"/resources","name":"NiFi Resources"},{"identifier":"/site-to-site","name":"Site to Site"},{"identifier":"/parameter-contexts","name":"Parameter Contexts"},{"identifier":"/restricted-components","name":"Restricted Components"},{"identifier":"/restricted-components/read-filesystem","name":"read filesystem"},{"identifier":"/restricted-components/write-filesystem","name":"write filesystem"},{"identifier":"/restricted-components/read-distributed-filesystem","name":"read distributed filesystem"},{"identifier":"/restricted-components/write-distributed-filesystem","name":"write distributed filesystem"},{"identifier":"/restricted-components/execute-code","name":"execute code"},{"identifier":"/restricted-components/access-keytab","name":"access keytab"},{"identifier":"/restricted-components/access-ticket-cache","name":"access ticket cache"},{"identifier":"/restricted-components/export-nifi-details","name":"export nifi details"},{"identifier":"/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"NiFi Flow"},{"identifier":"/data/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Data for NiFi Flow"},{"identifier":"/provenance-data/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Provenance data for NiFi Flow"},{"identifier":"/policies/process-groups/ad20fee5-017e-1000-9155-7e71f5041700","name":"Policies for NiFi Flow"},{"identifier":"/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"PutMongoRecord"},{"identifier":"/data/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/af20a99a-0181-1000-2f59-0444d2774410","name":"Operations forPutMongoRecord"},{"identifier":"/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"PutMongoRecord"},{"identifier":"/data/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/63c1f95d-0182-1000-ba33-adb87022b43a","name":"Operations forPutMongoRecord"},{"identifier":"/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"GetSFTP"},{"identifier":"/data/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/63c19043-0182-1000-98a3-60fd4f5fe3a7","name":"Operations forGetSFTP"},{"identifier":"/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"SplitJson"},{"identifier":"/data/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Data for SplitJson"},{"identifier":"/provenance-data/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Provenance data for SplitJson"},{"identifier":"/policies/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Policies for SplitJson"},{"identifier":"/operation/processors/aefcde88-0181-1000-00f9-794bac5f8dd0","name":"Operations forSplitJson"},{"identifier":"/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"PutMongoRecord"},{"identifier":"/data/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/4689b107-0180-1000-6bea-9a4d1811e266","name":"Operations forPutMongoRecord"},{"identifier":"/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"GetSFTP"},{"identifier":"/data/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/40b69fef-017f-1000-f905-1c02744e6cc1","name":"Operations forGetSFTP"},{"identifier":"/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"ConsumeKafka_2_6"},{"identifier":"/data/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Data for ConsumeKafka_2_6"},{"identifier":"/provenance-data/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Provenance data for ConsumeKafka_2_6"},{"identifier":"/policies/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Policies for ConsumeKafka_2_6"},{"identifier":"/operation/processors/6fd6fd1a-0180-1000-5ed3-5913de2ad77b","name":"Operations forConsumeKafka_2_6"},{"identifier":"/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"PutMongoRecord"},{"identifier":"/data/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/01801011-fd1a-1fd6-5bd7-67b635066cd4","name":"Operations forPutMongoRecord"},{"identifier":"/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"PutMongoRecord"},{"identifier":"/data/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Data for PutMongoRecord"},{"identifier":"/provenance-data/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Provenance data for PutMongoRecord"},{"identifier":"/policies/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Policies for PutMongoRecord"},{"identifier":"/operation/processors/01801009-fd1a-1fd6-bffc-5e611a9d3a1a","name":"Operations forPutMongoRecord"},{"identifier":"/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"GetSFTP"},{"identifier":"/data/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Data for GetSFTP"},{"identifier":"/provenance-data/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Provenance data for GetSFTP"},{"identifier":"/policies/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Policies for GetSFTP"},{"identifier":"/operation/processors/01801007-fd1a-1fd6-b510-b1e1aa1287df","name":"Operations forGetSFTP"},{"identifier":"/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"ConsumeKafka_2_6"},{"identifier":"/data/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Data for ConsumeKafka_2_6"},{"identifier":"/provenance-data/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Provenance data for ConsumeKafka_2_6"},{"identifier":"/policies/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Policies for ConsumeKafka_2_6"},{"identifier":"/operation/processors/0180100d-fd1a-1fd6-3bf3-84440354bc55","name":"Operations forConsumeKafka_2_6"},{"identifier":"/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"SplitJson"},{"identifier":"/data/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Data for SplitJson"},{"identifier":"/provenance-data/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Provenance data for SplitJson"},{"identifier":"/policies/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Policies for SplitJson"},{"identifier":"/operation/processors/0180100f-fd1a-1fd6-9b43-5de9b21cbe7e","name":"Operations forSplitJson"},{"identifier":"/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"flow"},{"identifier":"/data/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Data for flow"},{"identifier":"/provenance-data/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Provenance data for flow"},{"identifier":"/policies/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Policies for flow"},{"identifier":"/operation/process-groups/01801005-fd1a-1fd6-8aa9-55ee4f211a02","name":"Operations forflow"},{"identifier":"/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"MongoDBControllerService"},{"identifier":"/policies/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Policies for MongoDBControllerService"},{"identifier":"/operation/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Operations forMongoDBControllerService"},{"identifier":"/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"CSVReader"},{"identifier":"/policies/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Policies for CSVReader"},{"identifier":"/operation/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Operations forCSVReader"},{"identifier":"/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"HBase_1_1_2_ClientService"},{"identifier":"/policies/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Policies for HBase_1_1_2_ClientService"},{"identifier":"/operation/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Operations forHBase_1_1_2_ClientService"},{"identifier":"/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"JsonTreeReader"},{"identifier":"/policies/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Policies for JsonTreeReader"},{"identifier":"/operation/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Operations forJsonTreeReader"},{"identifier":"/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"MongoDBControllerService"},{"identifier":"/policies/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Policies for MongoDBControllerService"},{"identifier":"/operation/controller-services/4693ed34-0180-1000-e53c-a512b52f2c1e","name":"Operations forMongoDBControllerService"},{"identifier":"/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"CSVReader"},{"identifier":"/policies/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Policies for CSVReader"},{"identifier":"/operation/controller-services/b0760bc1-017e-1000-112e-c273475ef010","name":"Operations forCSVReader"},{"identifier":"/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"HBase_1_1_2_ClientService"},{"identifier":"/policies/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Policies for HBase_1_1_2_ClientService"},{"identifier":"/operation/controller-services/e911d841-017e-1000-7b49-b8a043b84801","name":"Operations forHBase_1_1_2_ClientService"},{"identifier":"/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"JsonTreeReader"},{"identifier":"/policies/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Policies for JsonTreeReader"},{"identifier":"/operation/controller-services/af232dc6-0181-1000-e95f-6fdde81a3243","name":"Operations forJsonTreeReader"},{"identifier":"/templates/bd548bb1-87a0-4384-9fb5-06de55df2350","name":"test"},{"identifier":"/policies/templates/bd548bb1-87a0-4384-9fb5-06de55df2350","name":"Policies for test"}]}'
export pg_id_string=`echo $resources| jq -c '.resources[] | select(.name| contains ("'$pg_name'")) | .identifier' | grep -v 'data\|policies\|operation' | grep 'process-groups' | tr -d '"'`
echo $pg_id_string
```
